import { IExperience } from '../component/experience/IExperience';

const experience: IExperience.Payload = {
  disable: false,
  disableTotalPeriod: false,
  list: [
    {
      title: 'Outlier',
      position: 'DevOps Engineer',
      startedAt: '2023-12',
      endedAt: '',
      descriptions: [
        'GitHub Actions와 AWS CodePipeline을 활용해 CI/CD 파이프라인을 자동화, 배포 시간을 70% 단축하고 무중단 배포를 실현',
        'AWS EKS 상에서 Kubernetes 인프라를 운영하며 Pod 오토스케일링 및 롤링 업데이트를 개선, 서비스 중단을 80% 감소',
        'Terraform을 활용한 IaC(Infrastructure as Code)를 통해 VPC, RDS, IAM 역할, EKS 클러스터 등의 AWS 리소스를 프로비저닝 및 관리하여 인프라 일관성을 높이고 초기 셋업 시간을 60% 절감',
        'Prometheus와 Grafana를 통합하여 실시간 시스템 모니터링 및 알림 기능을 구축, 장애 대응 시간을 50% 이상 단축',
        'CPU/메모리 메트릭 및 APM 도구를 활용한 리소스 최적화 전략을 구현하여, 성능 저하 없이 클라우드 비용을 30% 절감',
      ],
      skillKeywords: [
        'AWS',
        'Docker',
        'Kubernetes',
        'Terraform',
        'CI/CD',
        'Prometheus',
        'Grafana',
        'Ansible',
        'Python',
      ],
    },
    {
      title: 'Ninehire',
      position: '소프트웨어 엔지니어',
      startedAt: '2023-08',
      endedAt: '2023-11',
      descriptions: [
        'TypeScript와 Nest.js를 사용하여 백엔드 REST API를 개발, 새로운 백엔드 페이지를 구현 및 서버 관리',
        'AWS ECS를 활용하여 새로운 기능을 배포, CI/CD를 통해 워크플로우를 자동화',
        '새로운 백엔드 기능과의 통합을 위해 데이터베이스 쿼리와 스키마를 최적화',
        '외부 서비스에서 나인하이어로의 데이터 마이그레이션 수행 및 관리',
        '배포 과정의 일환으로 QA 테스트 및 크로스 디바이스 호환성 검사를 수행하여 버그 식별 및 수정 그리고 개선 사항 제안',
        '지속적인 모니터링 및 실시간 버그 대응',
      ],
      skillKeywords: [
        'Typescript',
        'Nest.js',
        'Node.js',
        'AWS',
        'Docker',
        'MySQL',
        'Python',
        'CI/CD',
      ],
    },
    {
      title: '베스핀글로벌',
      position: 'DevOps Engineer',
      startedAt: '2022-02',
      endedAt: '2023-05',
      descriptions: [
        'AWS 서비스 구축 및 장애 대응 (VPC, EC2, RDS, ELB, Route53, IAM, S3, EKS, ECS, Lambda, EventBridge, API Gateway, Amplify, etc.)',
        '서비스 CI/CD 자동화 구현으로 서비스 빌드 및 배포 시간 70% 이상 단축 및 개발자 커뮤니케이션 비용 30% 이상 감소',
        '기존 고객사 서버 CPU, Memory, APM 분석으로 인한 최적화 인스턴스 타입 솔루션 제공으로 AWS 인프라 비용 30% 이상 감소',
        '고객사 서버 및 MSA 시스템 요소 관리, Metric 수집 및 모니터링으로 인한 실시간 대응으로 시스템 장애 원인 파악 및 처리, 장애발생 80% 감소',
        'AWS EKS Kubernetes 클러스터 및 노드 업데이트, 서비스 운영 관리, 장애 대응, 매일 하드웨어 상태 검사 및 AWS 이슈 확인으로 시스템 장애발생 80% 감소',
        'Terraform 모듈과 원격 백엔드를 사용하여 다중 환경 배포를 효과적으로 관리',
        'Linux 및 Windows OS 관리 및 장애 대응으로 장애 처리율 99% 이상',
        'Nginx, Apache 및 Tomcat 웹 서버 관리 및 장애 대응으로 장애 처리율 99% 이상',
        '고객사 플랫폼 서비스 On-premise 환경에서 AWS Cloud 환경으로 마이그레이션 진행',
        '자사 내부 보안 담당 (PC 보안 및 Okta 인증 솔루션 관리)',
      ],
      skillKeywords: [
        'AWS',
        'Docker',
        'Kubernetes',
        'CI/CD',
        'Terraform',
        'Ansible',
        'Node.js',
        'Apache',
        'Nginx',
        'Tomcat',
        'Whatap',
        'Slack',
        'Jira',
        'Confluence',
        'Jmeter',
        'Python',
      ],
    },
    {
      title: '베스핀글로벌',
      position: 'Internship & Trainee',
      startedAt: '2021-08',
      endedAt: '2022-02',
      descriptions: [
        'AWS 서비스 구축 및 장애 대응 (VPC, EC2, RDS, ELB, Route53, IAM, S3, EKS, ECS, Lambda, EventBridge, API Gateway, Amplify, etc.)',
        '서비스 CI/CD 자동화 구현으로 서비스 빌드 및 배포 시간 70% 이상 단축 및 개발자 커뮤니케이션 비용 30% 이상 감소',
        '기존 고객사 서버 CPU, Memory, APM 분석으로 인한 최적화 인스턴스 타입 솔루션 제공으로 AWS 인프라 비용 30% 이상 감소',
        '고객사 서버 및 MSA 시스템 요소 관리, Metric 수집 및 모니터링으로 인한 실시간 대응으로 시스템 장애 원인 파악 및 처리, 장애발생 80% 감소',
        'AWS EKS Kubernetes 클러스터 및 노드 업데이트, 서비스 운영 관리, 장애 대응, 매일 하드웨어 상태 검사 및 AWS 이슈 확인으로 시스템 장애발생 80% 감소',
        'Terraform 모듈과 원격 백엔드를 사용하여 다중 환경 배포를 효과적으로 관리',
        'Linux 및 Windows OS 관리 및 장애 대응으로 장애 처리율 99% 이상',
        'Nginx, Apache 및 Tomcat 웹 서버 관리 및 장애 대응으로 장애 처리율 99% 이상',
        '고객사 플랫폼 서비스 On-premise 환경에서 AWS Cloud 환경으로 마이그레이션 진행',
        '자사 내부 보안 담당 (PC 보안 및 Okta 인증 솔루션 관리)',
      ],
      skillKeywords: [
        'AWS',
        'Docker',
        'Kubernetes',
        'CI/CD',
        'Terraform',
        'Ansible',
        'Node.js',
        'Apache',
        'Nginx',
        'Tomcat',
        'Whatap',
        'Slack',
        'Jira',
        'Confluence',
        'Jmeter',
        'Python',
      ],
    },
    // {
    //   title: '부산 IT 인재 개발원',
    //   position: 'Trainee',
    //   startedAt: '2020-12',
    //   endedAt: '2021-07',
    //   descriptions: [
    //     '빅데이터 기술(빅데이터 수집, 저장, 분석, 시각화)',
    //     'Restful API 서버 구축',
    //     'UI 표준화에 의한 구현 기술을 사용하여 웹 & 모바일 소프트웨어 개발',
    //     '자료구조 및 알고리즘',
    //   ],
    //   skillKeywords: [
    //     'Python',
    //     'Java',
    //     'Spring',
    //     'React.js',
    //     'MySQL',
    //     'OracleDB',
    //     'Firebase',
    //     'MySQL',
    //     'JavaScript',
    //     'HTML',
    //     'CSS',
    //   ],
    // },
  ],
};

export default experience;
