import { IExperience } from '../component/experience/IExperience';

const experience: IExperience.Payload = {
  disable: false,
  disableTotalPeriod: false,
  list: [
    {
      title: 'Outlier',
      position: 'Full Stack Engineer',
      startedAt: '2024-12',
      endedAt: '',
      descriptions: [
        '웹 기반 UI 시스템을 개발하여 AI 모델의 동적 등록 및 Kubernetes Pod 자동 생성을 구현, 모델 배포 효율성 향상',
        'AI 워크로드 운영을 위한 Kubernetes 인프라를 설계 및 관리, 확장성과 안정성을 확보',
        '모델 간 순차 및 병렬 실행이 가능한 워크플로우 엔진을 구축하여 복잡한 파이프라인 구성 유연성 확보',
        'Kafka 기반의 비동기 메시징 시스템을 도입하여 모델 간 안정적인 데이터 파이프라인을 구성',
        '자동 및 수동 스케줄링 기능을 통해 대용량 배치 처리 자동화, 운영 리소스 절감',
        '사용자 스토리지 업로드를 실시간 감지하는 모니터링 시스템을 구현, 데이터 업로드 시 자동 워크플로우 실행',
        '다중 AI 컨테이너의 리소스 사용률, 추론 시간, 성능 지표를 실시간 수집 및 시각화하여 운영 리포트 자동 생성',
      ],
      skillKeywords: [
        'AWS',
        'Docker',
        'Kubernetes',
        'Terraform',
        'CI/CD',
        'Prometheus',
        'Grafana',
        'Ansible',
        'Python',
      ],
    },
    {
      title: 'Ninehire',
      position: '소프트웨어 엔지니어',
      startedAt: '2023-08',
      endedAt: '2023-11',
      descriptions: [
        'TypeScript와 Nest.js를 사용하여 백엔드 REST API를 개발, 새로운 백엔드 페이지를 구현 및 서버 관리',
        'AWS ECS를 활용하여 새로운 기능을 배포, CI/CD를 통해 워크플로우를 자동화',
        '새로운 백엔드 기능과의 통합을 위해 데이터베이스 쿼리와 스키마를 최적화',
        '외부 서비스에서 나인하이어로의 데이터 마이그레이션 수행 및 관리',
        '배포 과정의 일환으로 QA 테스트 및 크로스 디바이스 호환성 검사를 수행하여 버그 식별 및 수정 그리고 개선 사항 제안',
        '지속적인 모니터링 및 실시간 버그 대응',
      ],
      skillKeywords: [
        'Typescript',
        'Nest.js',
        'Node.js',
        'AWS',
        'Docker',
        'MySQL',
        'Python',
        'CI/CD',
      ],
    },
    {
      title: '베스핀글로벌',
      position: 'DevOps Engineer',
      startedAt: '2022-02',
      endedAt: '2023-05',
      descriptions: [
        'AWS 서비스 구축 및 장애 대응 (VPC, EC2, RDS, ELB, Route53, IAM, S3, EKS, ECS, Lambda, EventBridge, API Gateway, Amplify, etc.)',
        '서비스 CI/CD 자동화 구현으로 서비스 빌드 및 배포 시간 70% 이상 단축 및 개발자 커뮤니케이션 비용 30% 이상 감소',
        '기존 고객사 서버 CPU, Memory, APM 분석으로 인한 최적화 인스턴스 타입 솔루션 제공으로 AWS 인프라 비용 30% 이상 감소',
        '고객사 서버 및 MSA 시스템 요소 관리, Metric 수집 및 모니터링으로 인한 실시간 대응으로 시스템 장애 원인 파악 및 처리, 장애발생 80% 감소',
        'AWS EKS Kubernetes 클러스터 및 노드 업데이트, 서비스 운영 관리, 장애 대응, 매일 하드웨어 상태 검사 및 AWS 이슈 확인으로 시스템 장애발생 80% 감소',
        'Terraform 모듈과 원격 백엔드를 사용하여 다중 환경 배포를 효과적으로 관리',
        'Linux 및 Windows OS 관리 및 장애 대응으로 장애 처리율 99% 이상',
        'Nginx, Apache 및 Tomcat 웹 서버 관리 및 장애 대응으로 장애 처리율 99% 이상',
        '고객사 플랫폼 서비스 On-premise 환경에서 AWS Cloud 환경으로 마이그레이션 진행',
        '자사 내부 보안 담당 (PC 보안 및 Okta 인증 솔루션 관리)',
      ],
      skillKeywords: [
        'AWS',
        'Docker',
        'Kubernetes',
        'CI/CD',
        'Terraform',
        'Ansible',
        'Node.js',
        'Apache',
        'Nginx',
        'Tomcat',
        'Whatap',
        'Slack',
        'Jira',
        'Confluence',
        'Jmeter',
        'Python',
      ],
    },
    {
      title: '베스핀글로벌',
      position: 'Internship & Trainee',
      startedAt: '2021-08',
      endedAt: '2022-02',
      descriptions: [
        'AWS 서비스 구축 및 장애 대응 (VPC, EC2, RDS, ELB, Route53, IAM, S3, EKS, ECS, Lambda, EventBridge, API Gateway, Amplify, etc.)',
        '서비스 CI/CD 자동화 구현으로 서비스 빌드 및 배포 시간 70% 이상 단축 및 개발자 커뮤니케이션 비용 30% 이상 감소',
        '기존 고객사 서버 CPU, Memory, APM 분석으로 인한 최적화 인스턴스 타입 솔루션 제공으로 AWS 인프라 비용 30% 이상 감소',
        '고객사 서버 및 MSA 시스템 요소 관리, Metric 수집 및 모니터링으로 인한 실시간 대응으로 시스템 장애 원인 파악 및 처리, 장애발생 80% 감소',
        'AWS EKS Kubernetes 클러스터 및 노드 업데이트, 서비스 운영 관리, 장애 대응, 매일 하드웨어 상태 검사 및 AWS 이슈 확인으로 시스템 장애발생 80% 감소',
        'Terraform 모듈과 원격 백엔드를 사용하여 다중 환경 배포를 효과적으로 관리',
        'Linux 및 Windows OS 관리 및 장애 대응으로 장애 처리율 99% 이상',
        'Nginx, Apache 및 Tomcat 웹 서버 관리 및 장애 대응으로 장애 처리율 99% 이상',
        '고객사 플랫폼 서비스 On-premise 환경에서 AWS Cloud 환경으로 마이그레이션 진행',
        '자사 내부 보안 담당 (PC 보안 및 Okta 인증 솔루션 관리)',
      ],
      skillKeywords: [
        'AWS',
        'Docker',
        'Kubernetes',
        'CI/CD',
        'Terraform',
        'Ansible',
        'Node.js',
        'Apache',
        'Nginx',
        'Tomcat',
        'Whatap',
        'Slack',
        'Jira',
        'Confluence',
        'Jmeter',
        'Python',
      ],
    },
    // {
    //   title: '부산 IT 인재 개발원',
    //   position: 'Trainee',
    //   startedAt: '2020-12',
    //   endedAt: '2021-07',
    //   descriptions: [
    //     '빅데이터 기술(빅데이터 수집, 저장, 분석, 시각화)',
    //     'Restful API 서버 구축',
    //     'UI 표준화에 의한 구현 기술을 사용하여 웹 & 모바일 소프트웨어 개발',
    //     '자료구조 및 알고리즘',
    //   ],
    //   skillKeywords: [
    //     'Python',
    //     'Java',
    //     'Spring',
    //     'React.js',
    //     'MySQL',
    //     'OracleDB',
    //     'Firebase',
    //     'MySQL',
    //     'JavaScript',
    //     'HTML',
    //     'CSS',
    //   ],
    // },
  ],
};

export default experience;
