import { IExperience } from '../component/experience/IExperience';

const experience: IExperience.Payload = {
  disable: false,
  disableTotalPeriod: false,
  list: [
    {
      title: '베스핀글로벌 테크 센터',
      position: 'DevOps Engineer',
      startedAt: '2022-02',
      endedAt: '2023-04',
      descriptions: [
        'AWS 서비스 구축 및 장애 대응 (VPC, EC2, RDS, ELB, Route53, IAM, EKS, ECS, etc)',
        'Node.js 및 Java 환경 서비스 CI/CD 자동화 구현으로 서비스 빌드 및 배포 시간 70% 이상 단축 및 개발자 커뮤니케이션 비용 30% 이상 감소',
        '기존 고객사 서버 CPU, Memory, APM 분석으로 인한 최적화 인스턴스 타입 솔루션 제공으로 AWS 인프라 비용 30% 감소',
        'Linux 및 Windows OS 관리 및 장애 대응으로 장애 처리율 90% 이상',
        'Nginx, Apache 및 Tomcat 웹 서버 관리 및 장애 대응으로 장애 처리율 90% 이상',
        '고객사 서버 및 MSA 시스템 요소 관리, Metric 수집 및 모니터링으로 인한 실시간 대응으로 시스템 장애 원인 파악 및 처리, 장애발생 75% 감소',
        'AWS EKS Kubernetes 클러스터 및 노드 업데이트, 서비스 운영 관리, 장애 대응, 매일 하드웨어 상태 검사 및 AWS 이슈 확인으로 시스템 장애발생 80% 감소',
        '서버 및 데이터베이스 이중화 설치 및 연동',
        '고객사 플랫폼 서비스 On-premise 환경에서 AWS Cloud 환경으로 마이그레이션 진행',
        '자사 내부 보안 담당 (PC 보안 및 Okta 인증 솔루션 관리)',
      ],
      skillKeywords: [
        'AWS',
        'Docker',
        'Kubernetes',
        'CI/CD',
        'Terraform',
        'Ansible',
        'Node.js',
        'Apache',
        'Nginx',
        'Tomcat',
        'Whatap',
        'Slack',
      ],
    },
    {
      title: '베스핀글로벌',
      position: 'Trainee',
      startedAt: '2021-08',
      endedAt: '2021-12',
      descriptions: [
        '클라우드 서비스(AWS, GCP, Azure) 및 네트워크',
        'WEB, WAS, DB 3-tier 구축',
        'Docker, Kubernetes 구축 및 운영',
        'Linux 및 Windows OS',
        'Iac(Terraform 및 Ansible)를 이용한 코드를 이용한 인프라 구축',
        'Jenkins를 이용한 CI/CD 자동 빌드 및 배포',
        'JMeter 및 stress를 활용한 성능테스트',
      ],
      skillKeywords: [
        'AWS',
        'GCP',
        'Docker',
        'Kubernetes',
        'Terraform',
        'Ansible',
        'Jenkins',
        'CI/CD',
        'Jmeter',
      ],
    },
    {
      title: '부산 IT 인재 개발원',
      position: 'Trainee',
      startedAt: '2020-12',
      endedAt: '2021-07',
      descriptions: [
        '빅데이터 기술(빅데이터 수집, 저장, 분석, 시각화)',
        'Restful API 서버 구축',
        'UI 표준화에 의한 구현 기술을 사용하여 웹 & 모바일 소프트웨어 개발',
        '자료구조 및 알고리즘',
      ],
      skillKeywords: [
        'Python',
        'Java',
        'Spring',
        'React.js',
        'MySQL',
        'OracleDB',
        'Firebase',
        'MySQL',
        'JavaScript',
        'HTML',
        'CSS',
      ],
    },
  ],
};

export default experience;
